# Generated by Django 2.2.3 on 2019-07-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussiness_partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('date', models.DateField(verbose_name='Fecha para servicio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bussiness_partner.BussinessPartner', verbose_name='Cliente')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Asignacion orden de trabajo',
                'verbose_name_plural': 'Asignaciones orden de trabajo',
            },
        ),
    ]
