# Generated by Django 2.2.3 on 2019-07-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wo_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderassignment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.WorkerProfile', verbose_name='Técnico'),
        ),
    ]
