# Generated by Django 2.2.3 on 2019-08-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wo_assignments', '0002_auto_20190730_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderassignment',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
