# Generated by Django 2.2.3 on 2019-07-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='BussinessPartner',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Código')),
                ('f_name', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('s_name', models.CharField(max_length=50, verbose_name='Segundo Nombre')),
                ('l_name', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('ll_name', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('employe', models.CharField(max_length=200, verbose_name='Empresa')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono / Cel')),
                ('state', models.BooleanField(verbose_name='Estado')),
                ('address', models.ManyToManyField(to='bussiness_partner.Address', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Socio de negocio',
                'verbose_name_plural': 'Socios de negocio',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bussiness_partner.Zone', verbose_name='Zona'),
        ),
    ]
