# Generated by Django 2.2.3 on 2019-07-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependence',
            options={'verbose_name': 'Dependencias'},
        ),
    ]
